
---
- name: update web, nfs and db servers
  hosts: webservers, nfs, db
  become: yes
  tasks:
    - name: ensure wireshark is at the latest version
      yum:
        name: wireshark
        state: latest

- name: update lb server
  hosts: lb
  become: yes
  tasks:
    - name: Update apt repo
      apt: 
        update_cache: yes

   - name: ensure wireshark is at the latest version
     apt:
        name: wireshark
        state: latest

  tasks: 
    - name: Create a directory if it does not exist
        path: /home/ubuntu/ansible-jobs
        state: directory

  tasks:     
    - name: Create a file if it does not exist
        path: /home/ubuntu/ansible-jobs/testing.yml
        state: file