---
#- hosts: all
#- import_playbook: ../static-assignments/common.yml

#- hosts: all
#- import_playbook: ../static-assignments/common-del.yml
# samples



- hosts: all
- name: Include dynamic variables
  include: ../dynamic-assignments/env-vars.yml
  tags:
    - always 
    
- hosts: db
#- name: installing db
- import_playbook: ../static-assignments/db.yml

#- hosts: uat-webservers
#git- import_playbook: ../static-assignments/uat-webservers.yml


 #- hosts: all
 #- name: Include dynamic variables 
#    #tasks:
#    #import_playbook: ../static-assignments/db.yml 
#    #include: ../dynamic-assignments/env-vars.yml
#    #tags:
#     #- always

#-  hosts: webservers
#- name: Webserver assignment
# import_playbook: ../static-assignments/webservers.yml


