#[nfs]
#172.31.46.13 ansible_ssh_user='ec2-user'

#[webservers]
#172.31.41.249 ansible_ssh_user='ec2-user'
#172.31.41.13 ansible_ssh_user='ec2-user'

# [db]
# 172.31.41.198 ansible_ssh_user='ubuntu'

[lb]
#172.31.16.59 ansible_ssh_user='ubuntu'
172.31.19.169 ansible_ssh_user='ubuntu'
