---
# Variable configuration.
-  variables.yml

# Setup/install tasks.
- setup-RedHat.yml
  when: ansible_os_family == 'RedHat'

- setup-Debian.yml
  when: ansible_os_family == 'Debian'

- setup-Archlinux.yml
  when: ansible_os_family == 'Archlinux'

- name: Check if MySQL packages were installed.
  set_fact:
    mysql_install_packages: "{{ (rh_mysql_install_packages is defined and rh_mysql_install_packages.changed)
      or (deb_mysql_install_packages is defined and deb_mysql_install_packages.changed)
      or (arch_mysql_install_packages is defined and arch_mysql_install_packages.changed) }}"

# Configure MySQL.
- configure.yml
- secure-installation.yml
- databases.yml
- users.yml
- replication.yml
